/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { DeleteTrustedDeviceMutationResponse, DeleteTrustedDevicePathParams } from "../types/DeleteTrustedDevice.ts";
import { fetch } from "../.kubb/fetch.ts";

function getDeleteTrustedDeviceUrl(apiVersion: DeleteTrustedDevicePathParams["apiVersion"], deviceId: DeleteTrustedDevicePathParams["deviceId"]) {
  const res = { method: 'DELETE', url: `/${apiVersion}/profile/devices/${deviceId}` as const }  
  return res
}

/**
 * @description Revoke an active trusted device for your user.  Once a trusted device is revoked, this device will have to log in again before accessing your account.<<LB>>---- __CLI__.    ```    linode-cli profile device-revoke 123    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Revoke a trusted device
 * {@link /:apiVersion/profile/devices/:deviceId}
 */
export async function deleteTrustedDevice(apiVersion: DeleteTrustedDevicePathParams["apiVersion"], deviceId: DeleteTrustedDevicePathParams["deviceId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteTrustedDeviceMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteTrustedDeviceUrl(apiVersion, deviceId).url.toString(), ... requestConfig })  
  return res.data
}