/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { GetInvoicesQueryResponse, GetInvoicesPathParams, GetInvoicesQueryParams, GetInvoicesHeaderParams } from "../types/GetInvoices.ts";
import { fetch } from "../.kubb/fetch.ts";

function getGetInvoicesUrl(apiVersion: GetInvoicesPathParams["apiVersion"]) {
  const res = { method: 'GET', url: `/${apiVersion}/account/invoices` as const }  
  return res
}

/**
 * @description Returns a paginated list of invoices against your account.<<LB>>---- __CLI__.    ```    linode-cli account invoices-list    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary List invoices
 * {@link /:apiVersion/account/invoices}
 */
export async function getInvoices(apiVersion: GetInvoicesPathParams["apiVersion"], params?: GetInvoicesQueryParams, headers?: GetInvoicesHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetInvoicesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetInvoicesUrl(apiVersion).url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}